[build-system]
build-backend = "uv_build"
requires = ["uv_build>=0.11.6,<0.12"]

[dependency-groups]
dev = [
  "pdbpp>=0.12.1"
]
test = [
  "pytest>=8.3.4"
]

[project]
name = "range-streams"
version = "1.4.0"
description = "Streaming via range requests in Python"
readme = "README.md"
authors = [
  {name = "Louis Maddox", email = "louismmx@gmail.com"}
]
requires-python = ">=3.10"
dependencies = [
  "aiostream>=0.7.1",
  "httpx>=0.28.1",
  "python-ranges>=1.2.2",
  "pyzstd>=0.19.1",
  "tqdm>=4.67.3"
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15"
]

[project.license]
text = "MIT"

[tool.coverage.paths]
source = ["src", ".tox/*/site-packages"]

[tool.coverage.report]
show_missing = true
skip_covered = true

[tool.coverage.run]
parallel = true
branch = true
source = ["range_streams"]

[tool.ruff.lint]
ignore = ["E402"]

[tool.uv]
default-groups = "all"
